[package]
name = "lens-system"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true
crossterm.workspace = true
lens-model = { path = "../model", version = "=0.2.0" }
lens-platform-linux = { path = "../platform-linux", version = "=0.2.0" }
serde.workspace = true
serde_json.workspace = true
time.workspace = true

[lints]
workspace = true
