[package]
name = "lens-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
crossterm.workspace = true
lens-core = { path = "../core" }
lens-model = { path = "../model" }
lens-output = { path = "../output" }
ratatui.workspace = true
thiserror.workspace = true
unicode-width.workspace = true

[dev-dependencies]
insta.workspace = true
