[package]
name = "lens-output"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
lens-model = { version = "=0.3.1", path = "../model" }
serde.workspace = true
serde_json.workspace = true
unicode-width.workspace = true

[dev-dependencies]
insta.workspace = true
