[package]
name = "lens-system-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lens-system = { path = "../../crates/system", version = "=0.3.3" }

[[bin]]
name = "lens-system"
path = "src/main.rs"

[lints]
workspace = true
