[package]
name = "lens-services"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lens-system = { path = "../../crates/system", version = "=0.3.1" }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
